### ISSUE TITLE
About this repository

### ISSUE THREAD

**Issue by eblanca** [rbrito/lame#1]
Hello,
I just stumbled into this repository and so I see the lame development is still going on! Great!
The description says "Unofficial mirror of the CVS repository...", is that the one hosted on sourceforge?
(Why are you still developing in CVS?)
Are you devs fixing all the bugs reported on sourceforge tracking?
Will you receive contribution through github pull requests?
Thank you
Elio

**Comment by lordmulder** [comment]
I've just checked, looks like this Git repo is "up-to-date" with latest "official" CVS on SF.net:
http://lame.cvs.sourceforge.net/viewvc/lame/lame/libmp3lame/?sortby=date

Latest commit in CVS seems to be (although a bit hard to find in CVS) this one:
```
Revision 1.29
Fri Jan 29 21:36:34 2016 UTC (14 months, 3 weeks ago) by aleidinger
Branch: MAIN
CVS Tags: HEAD
Changes since 1.28: +451 -289 lines
Diff to previous 1.28

update history
```

...which matches latest Git commit https://github.com/rbrito/lame/commit/bb022ed2c83830aa4d0fb0dd457d0c499d7afef1 in rbrito's mirror.

----------

BTW: I assume the LAME developers started with CVS, because this was the "state of the art" when they started development of LAME. Then they never bothered moving to SVN or Git - especially because development of LAME had pretty much faded around the time when everyone moved to Git and GitHub.
